# Generated by Django 2.2.3 on 2020-08-06 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment',
            field=models.TextField(default='', max_length=1000, verbose_name='留言(清洗后)'),
        ),
    ]
